# IPF RANKINGS

In [67]:
import pandas as pd
pd.options.display.max_rows = 20

## UREJANJE PODATKOV
Preberemo csv, združimo v tabeli *moski* in *zenske*.

In [68]:
MM1 = pd.read_csv("uvoz_podatkov/6th_world_classic_MM1.csv", index_col = "ID_tekmovalca")
MM2 = pd.read_csv("uvoz_podatkov/6th_world_classic_MM2.csv", index_col = "ID_tekmovalca")
MM3 = pd.read_csv("uvoz_podatkov/6th_world_classic_MM3.csv", index_col = "ID_tekmovalca")
MM4 = pd.read_csv("uvoz_podatkov/6th_world_classic_MM4.csv", index_col = "ID_tekmovalca")

WM1 = pd.read_csv("uvoz_podatkov/6th_world_classic_WM1.csv", index_col = "ID_tekmovalca")
WM2 = pd.read_csv("uvoz_podatkov/6th_world_classic_WM2.csv", index_col = "ID_tekmovalca")
WM3 = pd.read_csv("uvoz_podatkov/6th_world_classic_WM3.csv", index_col = "ID_tekmovalca")
WM4 = pd.read_csv("uvoz_podatkov/6th_world_classic_WM4.csv", index_col = "ID_tekmovalca")

wMM1 = pd.read_csv("uvoz_podatkov/world_masters_MM1.csv", index_col = "ID_tekmovalca")
wMM2 = pd.read_csv("uvoz_podatkov/world_masters_MM2.csv", index_col = "ID_tekmovalca")
wMM3 = pd.read_csv("uvoz_podatkov/world_masters_MM3.csv", index_col = "ID_tekmovalca")
wMM4 = pd.read_csv("uvoz_podatkov/world_masters_MM4.csv", index_col = "ID_tekmovalca")

wWM1 = pd.read_csv("uvoz_podatkov/world_masters_WM1.csv", index_col = "ID_tekmovalca")
wWM2 = pd.read_csv("uvoz_podatkov/world_masters_WM2.csv", index_col = "ID_tekmovalca")
wWM3 = pd.read_csv("uvoz_podatkov/world_masters_WM3.csv", index_col = "ID_tekmovalca")
wWM4 = pd.read_csv("uvoz_podatkov/world_masters_WM4.csv", index_col = "ID_tekmovalca")

moski = pd.concat([MM1, MM2, MM3, MM4, wMM1, wMM2, wMM3, wMM4])
zenske = pd.concat([WM1, WM2, WM3, WM4, wWM1, wWM2, wWM3, wWM4])

V tabeli *moski* in *zenske* dodamo nov stolpec *kategorija*, v katerem so kategorije v katero tekmovalec spada. Tabeli nato združimo v tabelo *tekmovalci*.

In [69]:
def kategorija_m(s):
    if (s['teza'] <= 59):
        return 'moški 59 kg'
    elif (s['teza'] <= 66):
        return 'moški 66 kg'
    elif (s['teza'] <= 74):
        return 'moški 74 kg'
    elif (s['teza'] <= 83):
        return 'moški 83 kg'
    elif (s['teza'] <= 93):
        return 'moški 93 kg'
    elif (s['teza'] <= 105):
        return 'moški 105 kg'
    elif (s['teza'] <= 120):
        return 'moški 120 kg'
    else:
        return 'moški +120 kg'
    
def kategorija_z(s):
    if (s['teza'] <= 47):
        return 'ženske 47 kg'
    elif (s['teza'] <= 52):
        return 'ženske 52 kg'
    elif (s['teza'] <= 57):
        return 'ženske 57 kg'
    elif (s['teza'] <= 63):
        return 'ženske 63 kg'
    elif (s['teza'] <= 72):
        return 'ženske 72 kg'
    elif (s['teza'] <= 84):
        return 'ženske 84 kg'
    else:
        return 'ženske +84 kg'

MM['kategorija'] = MM.apply(kategorija_m, axis=1)
WM['kategorija'] = WM.apply(kategorija_z, axis=1)
tekmovalci = pd.concat([MM, WM])
tekmovalci

,uvrstitev,ime,razred,letnica_rojstva,drzava,teza,pocep,potisk_s_prsi,mrtvi_dvig,skupaj,tocke,kategorija
ID_tekmovalca,,,,,,,,,,,,
1016033,1,Śledż Sławomir,M1,1976,Poland,58.57,185,140,200,525,457.85,moški 59 kg
1016034,2,Brinker Ron,M1,1975,USA,58.35,152,100,177,430,376.33,moški 59 kg
1016035,1,Alcantara Anderson,M1,1976,Brazil,65.67,195,135,270,600,473.46,moški 66 kg
1016036,2,Noppers Lewis,M1,1970,Canada,65.53,195,135,255,585,462.06,moški 66 kg
1016037,3,Rheaume Jean-Sebastien,M1,1974,Canada,65.70,205,130,235,570,449.25,moški 66 kg
1016038,4,Murray Greig,M1,1971,Great Britain,65.10,165,127,232,525,416.94,moški 66 kg
1016039,5,Cagliola Michael,M1,1970,USA,65.70,177,132,215,525,413.78,moški 66 kg
1016040,6,Bernard Mikael,M1,1970,France,65.02,167,145,210,522,415.39,moški 66 kg
1016041,7,Hamilton-Smith Roger,M1,1975,Great Britain,65.18,180,115,225,520,412.55,moški 66 kg
1016042,8,McLaren Paul,M1,1974,Ireland,65.84,162,87,237,487,383.55,moški 66 kg
...,...,...,...,...,...,...,...,...,...,...,...,...
1044506,1,Marksteiner Cathleen,M3,1958,USA,63.30,95,75,140,310,331.73,ženske 72 kg
1044507,1,Takáčová Hana,M3,1954,Czech Republic,85.50,190,132,160,483,427.00,ženske +84 kg
1044508,2,Hallen Susan,M3,1957,USA,105.50,170,105,155,430,352.94,ženske +84 kg
1044509,1,Kumpuniemi Eila,M4,1942,Finland,46.48,90,45,100,235,319.26,ženske 47 kg
1044510,1,Elwyn Susan,M4,1947,USA,47.30,100,45,130,275,368.15,ženske 52 kg
1044511,2,Burns Bebe,M4,1942,USA,50.60,77,42,90,210,267.34,ženske 52 kg
1044512,1,Malicot Maryse,M4,1946,France,52.50,90,45,95,230,284.61,ženske 57 kg
1044513,2,Uvachan Nadezhda,M4,1944,Russia,55.20,80,45,85,210,249.89,ženske 57 kg
1044514,1,Fomina Tatyana,M4,1946,Russia,60.35,115,50,130,295,327.97,ženske 63 kg
1044515,1,Moore Gail,M4,1947,USA,71.40,130,87,142,360,353.35,ženske 72 kg

In [74]:
tekmovalci_po_letih = tekmovalci.groupby('letnica_rojstva')
tekmovalci_po_letih.count()

,uvrstitev,ime,razred,drzava,teza,pocep,potisk_s_prsi,mrtvi_dvig,skupaj,tocke,kategorija
letnica_rojstva,,,,,,,,,,,
1932,1,1,1,1,1,1,1,1,1,1,1
1937,1,1,1,1,1,1,1,1,1,1,1
1938,1,1,1,1,1,1,1,1,1,1,1
1940,4,4,4,4,4,4,4,4,4,4,4
1941,2,2,2,2,2,2,2,2,2,2,2
1942,6,6,6,6,6,6,6,6,6,6,6
1943,2,2,2,2,2,2,2,2,2,2,2
1944,4,4,4,4,4,4,4,4,4,4,4
1945,7,7,7,7,7,7,7,7,7,7,7
1946,7,7,7,7,7,7,7,7,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...
1970,18,18,18,18,18,18,18,18,18,18,18
1971,11,11,11,11,11,11,11,11,11,11,11
1972,10,10,10,10,10,10,10,10,10,10,10
1973,13,13,13,13,13,13,13,13,13,13,13
1974,21,21,21,21,21,21,21,21,21,21,21
1975,19,19,19,19,19,19,19,19,19,19,19
1976,18,18,18,18,18,18,18,18,18,18,18
1977,15,15,15,15,15,15,15,15,15,15,15
1978,19,19,19,19,19,19,19,19,19,19,19
1991,1,1,1,1,1,1,1,1,1,1,1